"""initial schema

Revision ID: 3d2e970677a0
Revises: 
Create Date: 2026-08-18 09:34:46.015230+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3d2e970677a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('input_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('risk_status', sa.String(length=48), nullable=True),
    sa.Column('execution_status', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_market_id'), 'audit_logs', ['market_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gamma_event_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('neg_risk', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_closed_end_date', 'events', ['closed', 'end_date'], unique=False)
    op.create_index(op.f('ix_events_gamma_event_id'), 'events', ['gamma_event_id'], unique=True)
    op.create_table('external_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.Column('health', sa.String(length=48), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('success_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint('source_tier BETWEEN 1 AND 4', name=op.f('ck_external_sources_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_external_sources_name'))
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('feature_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'version', name='model_id_version')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('scope_value', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metrics'))
    )
    op.create_index(op.f('ix_performance_metrics_computed_at'), 'performance_metrics', ['computed_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_kind'), 'performance_metrics', ['kind'], unique=False)
    op.create_index('ix_performance_metrics_kind_scope', 'performance_metrics', ['kind', 'scope', 'scope_value'], unique=False)
    op.create_index(op.f('ix_performance_metrics_model_version'), 'performance_metrics', ['model_version'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('venue', sa.String(length=48), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_usd', sa.Float(), nullable=False),
    sa.Column('positions_value_usd', sa.Float(), nullable=False),
    sa.Column('equity_usd', sa.Float(), nullable=False),
    sa.Column('unrealised_pnl_usd', sa.Float(), nullable=False),
    sa.Column('realised_pnl_usd', sa.Float(), nullable=False),
    sa.Column('open_position_count', sa.Integer(), nullable=False),
    sa.Column('gross_exposure_usd', sa.Float(), nullable=False),
    sa.Column('max_concentration_pct', sa.Float(), nullable=True),
    sa.Column('peak_equity_usd', sa.Float(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_taken_at'), 'portfolio_snapshots', ['taken_at'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('event', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=48), nullable=True),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index('ix_system_events_component_occurred', 'system_events', ['component', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_system_events_correlation_id'), 'system_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_events_event'), 'system_events', ['event'], unique=False)
    op.create_index(op.f('ix_system_events_occurred_at'), 'system_events', ['occurred_at'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gamma_market_id', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('question_id', sa.String(length=80), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_item_title', sa.Text(), nullable=True),
    sa.Column('resolution_source', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=80), nullable=True),
    sa.Column('uma_resolution_statuses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('accepting_orders', sa.Boolean(), nullable=True),
    sa.Column('enable_order_book', sa.Boolean(), nullable=True),
    sa.Column('neg_risk', sa.Boolean(), nullable=True),
    sa.Column('neg_risk_market_id', sa.String(length=80), nullable=True),
    sa.Column('liquidity_num', sa.Float(), nullable=True),
    sa.Column('volume_num', sa.Float(), nullable=True),
    sa.Column('volume_24hr', sa.Float(), nullable=True),
    sa.Column('order_min_size', sa.Float(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modelability_status', sa.String(length=48), nullable=False),
    sa.Column('modelability_score', sa.Float(), nullable=True),
    sa.Column('modelability_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_markets_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets'))
    )
    op.create_index(op.f('ix_markets_condition_id'), 'markets', ['condition_id'], unique=False)
    op.create_index(op.f('ix_markets_end_date'), 'markets', ['end_date'], unique=False)
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_gamma_market_id'), 'markets', ['gamma_market_id'], unique=True)
    op.create_index(op.f('ix_markets_last_seen_at'), 'markets', ['last_seen_at'], unique=False)
    op.create_index('ix_markets_modelability_liquidity', 'markets', ['modelability_status', 'liquidity_num'], unique=False)
    op.create_index(op.f('ix_markets_modelability_status'), 'markets', ['modelability_status'], unique=False)
    op.create_index(op.f('ix_markets_neg_risk_market_id'), 'markets', ['neg_risk_market_id'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_index('ix_markets_status_category', 'markets', ['status', 'category'], unique=False)
    op.create_table('external_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=False),
    sa.Column('reference_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=48), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_external_events_market_id_markets')),
    sa.ForeignKeyConstraint(['source_id'], ['external_sources.id'], name=op.f('fk_external_events_source_id_external_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_events')),
    sa.UniqueConstraint('source_id', 'content_hash', name='source_content')
    )
    op.create_index(op.f('ix_external_events_known_at'), 'external_events', ['known_at'], unique=False)
    op.create_index(op.f('ix_external_events_market_id'), 'external_events', ['market_id'], unique=False)
    op.create_index('ix_external_events_market_known', 'external_events', ['market_id', 'known_at'], unique=False)
    op.create_index(op.f('ix_external_events_source_id'), 'external_events', ['source_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('midpoint', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('last_trade_price', sa.Float(), nullable=True),
    sa.Column('bid_depth_usd', sa.Float(), nullable=True),
    sa.Column('ask_depth_usd', sa.Float(), nullable=True),
    sa.Column('book_imbalance', sa.Float(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('data_latency_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint('(best_ask IS NULL OR (best_ask >= 0 AND best_ask <= 1))', name=op.f('ck_market_snapshots_best_ask_in_unit_interval')),
    sa.CheckConstraint('(best_bid IS NULL OR (best_bid >= 0 AND best_bid <= 1))', name=op.f('ck_market_snapshots_best_bid_in_unit_interval')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_snapshots_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots'))
    )
    op.create_index(op.f('ix_market_snapshots_known_at'), 'market_snapshots', ['known_at'], unique=False)
    op.create_index('ix_market_snapshots_market_known', 'market_snapshots', ['market_id', 'known_at'], unique=False)
    op.create_index('ix_market_snapshots_token_known', 'market_snapshots', ['token_id', 'known_at'], unique=False)
    op.create_table('market_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('outcome', sa.String(length=128), nullable=False),
    sa.Column('outcome_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_tokens_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_tokens')),
    sa.UniqueConstraint('market_id', 'outcome_index', name=op.f('uq_market_tokens_market_id_outcome_index'))
    )
    op.create_index(op.f('ix_market_tokens_market_id'), 'market_tokens', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_tokens_token_id'), 'market_tokens', ['token_id'], unique=True)
    op.create_table('order_book_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('book_hash', sa.String(length=96), nullable=True),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_order_book_snapshots_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_book_snapshots')),
    sa.UniqueConstraint('token_id', 'book_hash', 'observed_at', name='token_hash_observed')
    )
    op.create_index(op.f('ix_order_book_snapshots_known_at'), 'order_book_snapshots', ['known_at'], unique=False)
    op.create_index('ix_order_book_snapshots_token_known', 'order_book_snapshots', ['token_id', 'known_at'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('venue', sa.String(length=48), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_entry_price', sa.Float(), nullable=False),
    sa.Column('cost_basis_usd', sa.Float(), nullable=False),
    sa.Column('realised_pnl_usd', sa.Float(), nullable=False),
    sa.Column('fees_paid_usd', sa.Float(), nullable=False),
    sa.Column('slippage_paid_usd', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_positions_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('token_id', 'venue', 'opened_at', name='token_venue_open')
    )
    op.create_index(op.f('ix_positions_is_open'), 'positions', ['is_open'], unique=False)
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('executable_market_probability', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_uncertainty', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_latency_ms', sa.Integer(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_risk', sa.String(length=48), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_predictions_confidence_unit')),
    sa.CheckConstraint('market_probability >= 0 AND market_probability <= 1', name=op.f('ck_predictions_market_prob_unit')),
    sa.CheckConstraint('model_probability >= 0 AND model_probability <= 1', name=op.f('ck_predictions_model_prob_unit')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_predictions_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_known_at'), 'predictions', ['known_at'], unique=False)
    op.create_index(op.f('ix_predictions_market_id'), 'predictions', ['market_id'], unique=False)
    op.create_index('ix_predictions_market_predicted', 'predictions', ['market_id', 'predicted_at'], unique=False)
    op.create_index(op.f('ix_predictions_model_version'), 'predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=48), nullable=False),
    sa.Column('winning_outcome_index', sa.Integer(), nullable=True),
    sa.Column('resolution_source_text', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=80), nullable=True),
    sa.Column('uma_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_resolutions_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolutions')),
    sa.UniqueConstraint('market_id', name=op.f('uq_resolutions_market_id'))
    )
    op.create_index(op.f('ix_resolutions_known_at'), 'resolutions', ['known_at'], unique=False)
    op.create_index(op.f('ix_resolutions_outcome'), 'resolutions', ['outcome'], unique=False)
    op.create_index(op.f('ix_resolutions_resolved_at'), 'resolutions', ['resolved_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=True),
    sa.Column('side', sa.String(length=48), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_trades_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('external_id', name=op.f('uq_trades_external_id'))
    )
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_trades_traded_at'), 'trades', ['traded_at'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name=op.f('ck_model_predictions_component_prob_unit')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_model_predictions_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index(op.f('ix_model_predictions_model_version'), 'model_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_predictions_prediction_id'), 'model_predictions', ['prediction_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('side', sa.String(length=48), nullable=True),
    sa.Column('recommendation', sa.String(length=48), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('raw_edge', sa.Float(), nullable=False),
    sa.Column('executable_edge', sa.Float(), nullable=True),
    sa.Column('liquidity_adjusted_edge', sa.Float(), nullable=True),
    sa.Column('risk_adjusted_edge', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('executable_price', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('estimated_slippage', sa.Float(), nullable=True),
    sa.Column('execution_probability', sa.Float(), nullable=True),
    sa.Column('resolution_risk', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('rank_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('persistence_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edge_persisted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_signals_market_id_markets')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_signals_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_signals_idempotency_key'))
    )
    op.create_index(op.f('ix_signals_executable_edge'), 'signals', ['executable_edge'], unique=False)
    op.create_index(op.f('ix_signals_market_id'), 'signals', ['market_id'], unique=False)
    op.create_index(op.f('ix_signals_prediction_id'), 'signals', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_signals_recommendation'), 'signals', ['recommendation'], unique=False)
    op.create_index('ix_signals_recommendation_edge', 'signals', ['recommendation', 'executable_edge'], unique=False)
    op.create_index(op.f('ix_signals_signal_at'), 'signals', ['signal_at'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kill_switches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_size_usd', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_risk_decisions_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_decisions'))
    )
    op.create_index(op.f('ix_risk_decisions_signal_id'), 'risk_decisions', ['signal_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_status'), 'risk_decisions', ['status'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_decision_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('venue', sa.String(length=48), nullable=False),
    sa.Column('side', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=48), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('estimated_executable_price', sa.Float(), nullable=True),
    sa.Column('requested_size_usd', sa.Float(), nullable=False),
    sa.Column('signal_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_latency_ms', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("venue = 'PAPER'", name=op.f('ck_paper_orders_paper_orders_are_paper_only')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_paper_orders_market_id_markets')),
    sa.ForeignKeyConstraint(['risk_decision_id'], ['risk_decisions.id'], name=op.f('fk_paper_orders_risk_decision_id_risk_decisions')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_paper_orders_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_orders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_paper_orders_idempotency_key'))
    )
    op.create_index(op.f('ix_paper_orders_market_id'), 'paper_orders', ['market_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_signal_id'), 'paper_orders', ['signal_id'], unique=False)
    op.create_table('paper_fills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('side', sa.String(length=48), nullable=False),
    sa.Column('simulated_fill_price', sa.Float(), nullable=False),
    sa.Column('filled_size_usd', sa.Float(), nullable=False),
    sa.Column('filled_shares', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('book_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('simulated_fill_price >= 0 AND simulated_fill_price <= 1', name=op.f('ck_paper_fills_fill_price_unit')),
    sa.ForeignKeyConstraint(['book_snapshot_id'], ['order_book_snapshots.id'], name=op.f('fk_paper_fills_book_snapshot_id_order_book_snapshots')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_paper_fills_market_id_markets')),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], name=op.f('fk_paper_fills_order_id_paper_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_fills'))
    )
    op.create_index(op.f('ix_paper_fills_filled_at'), 'paper_fills', ['filled_at'], unique=False)
    op.create_index(op.f('ix_paper_fills_market_id'), 'paper_fills', ['market_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_order_id'), 'paper_fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_fills_order_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_market_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_filled_at'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_paper_orders_signal_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_market_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_risk_decisions_status'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_signal_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_signals_signal_at'), table_name='signals')
    op.drop_index('ix_signals_recommendation_edge', table_name='signals')
    op.drop_index(op.f('ix_signals_recommendation'), table_name='signals')
    op.drop_index(op.f('ix_signals_prediction_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_market_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_executable_edge'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_model_predictions_prediction_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_version'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_trades_traded_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_resolutions_resolved_at'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_outcome'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_known_at'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version'), table_name='predictions')
    op.drop_index('ix_predictions_market_predicted', table_name='predictions')
    op.drop_index(op.f('ix_predictions_market_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_known_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_open'), table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_order_book_snapshots_token_known', table_name='order_book_snapshots')
    op.drop_index(op.f('ix_order_book_snapshots_known_at'), table_name='order_book_snapshots')
    op.drop_table('order_book_snapshots')
    op.drop_index(op.f('ix_market_tokens_token_id'), table_name='market_tokens')
    op.drop_index(op.f('ix_market_tokens_market_id'), table_name='market_tokens')
    op.drop_table('market_tokens')
    op.drop_index('ix_market_snapshots_token_known', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_market_known', table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_known_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_external_events_source_id'), table_name='external_events')
    op.drop_index('ix_external_events_market_known', table_name='external_events')
    op.drop_index(op.f('ix_external_events_market_id'), table_name='external_events')
    op.drop_index(op.f('ix_external_events_known_at'), table_name='external_events')
    op.drop_table('external_events')
    op.drop_index('ix_markets_status_category', table_name='markets')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_neg_risk_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_modelability_status'), table_name='markets')
    op.drop_index('ix_markets_modelability_liquidity', table_name='markets')
    op.drop_index(op.f('ix_markets_last_seen_at'), table_name='markets')
    op.drop_index(op.f('ix_markets_gamma_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_end_date'), table_name='markets')
    op.drop_index(op.f('ix_markets_condition_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_system_events_occurred_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_correlation_id'), table_name='system_events')
    op.drop_index('ix_system_events_component_occurred', table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_portfolio_snapshots_taken_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_performance_metrics_model_version'), table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_kind_scope', table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_kind'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_computed_at'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_table('model_versions')
    op.drop_table('external_sources')
    op.drop_index(op.f('ix_events_gamma_event_id'), table_name='events')
    op.drop_index('ix_events_closed_end_date', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_market_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
