"""phase 1.5 evidence and features

Revision ID: d765ad5c0d73
Revises: 3d2e970677a0
Create Date: 2026-08-18 11:21:54.828834+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd765ad5c0d73'
down_revision = '3d2e970677a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.String(length=96), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('subcategory', sa.String(length=48), nullable=True),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_features_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_features')),
    sa.UniqueConstraint('token_id', 'feature_set_version', 'known_at', name='token_version_known')
    )
    op.create_index(op.f('ix_market_features_category'), 'market_features', ['category'], unique=False)
    op.create_index('ix_market_features_category_known', 'market_features', ['category', 'known_at'], unique=False)
    op.create_index(op.f('ix_market_features_feature_set_version'), 'market_features', ['feature_set_version'], unique=False)
    op.create_index(op.f('ix_market_features_known_at'), 'market_features', ['known_at'], unique=False)
    op.create_index(op.f('ix_market_features_market_id'), 'market_features', ['market_id'], unique=False)
    op.create_table('evidence_conflicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('series_key', sa.String(length=96), nullable=False),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('winning_evidence_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.String(length=48), nullable=False),
    sa.Column('resolution_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_evidence_conflicts_market_id_markets')),
    sa.ForeignKeyConstraint(['winning_evidence_id'], ['external_events.id'], name=op.f('fk_evidence_conflicts_winning_evidence_id_external_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_conflicts'))
    )
    op.create_index(op.f('ix_evidence_conflicts_detected_at'), 'evidence_conflicts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_evidence_conflicts_market_id'), 'evidence_conflicts', ['market_id'], unique=False)
    op.create_index(op.f('ix_evidence_conflicts_series_key'), 'evidence_conflicts', ['series_key'], unique=False)
    op.create_index('ix_evidence_conflicts_series_observation', 'evidence_conflicts', ['series_key', 'observation_date'], unique=False)
    op.create_table('market_evidence_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.BigInteger(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.String(length=128), nullable=False),
    sa.Column('match_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('relevance >= 0 AND relevance <= 1', name=op.f('ck_market_evidence_links_relevance_unit')),
    sa.ForeignKeyConstraint(['evidence_id'], ['external_events.id'], name=op.f('fk_market_evidence_links_evidence_id_external_events')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_evidence_links_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_evidence_links')),
    sa.UniqueConstraint('market_id', 'evidence_id', name='market_evidence')
    )
    op.create_index(op.f('ix_market_evidence_links_evidence_id'), 'market_evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_market_evidence_links_known_at'), 'market_evidence_links', ['known_at'], unique=False)
    op.create_index(op.f('ix_market_evidence_links_market_id'), 'market_evidence_links', ['market_id'], unique=False)
    op.create_index('ix_market_evidence_links_market_known', 'market_evidence_links', ['market_id', 'known_at'], unique=False)
    op.add_column('external_events', sa.Column('evidence_type', sa.String(length=48), nullable=True))
    op.add_column('external_events', sa.Column('series_key', sa.String(length=96), nullable=True))
    op.add_column('external_events', sa.Column('numeric_value', sa.Float(), nullable=True))
    op.add_column('external_events', sa.Column('unit', sa.String(length=32), nullable=True))
    op.add_column('external_events', sa.Column('observation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_events', sa.Column('superseded_by_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_external_events_evidence_type'), 'external_events', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_external_events_observation_date'), 'external_events', ['observation_date'], unique=False)
    op.create_index(op.f('ix_external_events_series_key'), 'external_events', ['series_key'], unique=False)
    op.create_index('ix_external_events_series_known', 'external_events', ['series_key', 'known_at'], unique=False)
    op.create_index('ix_external_events_series_observation', 'external_events', ['series_key', 'observation_date'], unique=False)
    op.add_column('external_sources', sa.Column('source_key', sa.String(length=64), nullable=True))
    op.add_column('external_sources', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('external_sources', sa.Column('access_method', sa.String(length=32), nullable=True))
    op.add_column('external_sources', sa.Column('update_frequency_s', sa.Integer(), nullable=True))
    op.add_column('external_sources', sa.Column('daily_request_budget', sa.Integer(), nullable=True))
    op.add_column('external_sources', sa.Column('requests_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('external_sources', sa.Column('budget_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_sources', sa.Column('parser_name', sa.String(length=64), nullable=True))
    op.add_column('external_sources', sa.Column('parser_version', sa.String(length=32), nullable=True))
    op.add_column('external_sources', sa.Column('terms_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_external_sources_source_key'), 'external_sources', ['source_key'], unique=True)
    op.add_column('markets', sa.Column('subcategory', sa.String(length=48), nullable=True))
    op.add_column('markets', sa.Column('event_type', sa.String(length=48), nullable=True))
    op.add_column('markets', sa.Column('resolution_mechanism', sa.String(length=48), nullable=True))
    op.add_column('markets', sa.Column('classification_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('markets', sa.Column('modelability_tier', sa.String(length=48), nullable=True))
    op.add_column('markets', sa.Column('evidence_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_markets_modelability_tier'), 'markets', ['modelability_tier'], unique=False)
    op.create_index(op.f('ix_markets_subcategory'), 'markets', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_subcategory'), table_name='markets')
    op.drop_index(op.f('ix_markets_modelability_tier'), table_name='markets')
    op.drop_column('markets', 'evidence_available')
    op.drop_column('markets', 'modelability_tier')
    op.drop_column('markets', 'classification_detail')
    op.drop_column('markets', 'resolution_mechanism')
    op.drop_column('markets', 'event_type')
    op.drop_column('markets', 'subcategory')
    op.drop_index(op.f('ix_external_sources_source_key'), table_name='external_sources')
    op.drop_column('external_sources', 'terms_url')
    op.drop_column('external_sources', 'parser_version')
    op.drop_column('external_sources', 'parser_name')
    op.drop_column('external_sources', 'budget_reset_at')
    op.drop_column('external_sources', 'requests_today')
    op.drop_column('external_sources', 'daily_request_budget')
    op.drop_column('external_sources', 'update_frequency_s')
    op.drop_column('external_sources', 'access_method')
    op.drop_column('external_sources', 'categories')
    op.drop_column('external_sources', 'source_key')
    op.drop_index('ix_external_events_series_observation', table_name='external_events')
    op.drop_index('ix_external_events_series_known', table_name='external_events')
    op.drop_index(op.f('ix_external_events_series_key'), table_name='external_events')
    op.drop_index(op.f('ix_external_events_observation_date'), table_name='external_events')
    op.drop_index(op.f('ix_external_events_evidence_type'), table_name='external_events')
    op.drop_column('external_events', 'superseded_by_id')
    op.drop_column('external_events', 'observation_date')
    op.drop_column('external_events', 'unit')
    op.drop_column('external_events', 'numeric_value')
    op.drop_column('external_events', 'series_key')
    op.drop_column('external_events', 'evidence_type')
    op.drop_index('ix_market_evidence_links_market_known', table_name='market_evidence_links')
    op.drop_index(op.f('ix_market_evidence_links_market_id'), table_name='market_evidence_links')
    op.drop_index(op.f('ix_market_evidence_links_known_at'), table_name='market_evidence_links')
    op.drop_index(op.f('ix_market_evidence_links_evidence_id'), table_name='market_evidence_links')
    op.drop_table('market_evidence_links')
    op.drop_index('ix_evidence_conflicts_series_observation', table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_series_key'), table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_market_id'), table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_detected_at'), table_name='evidence_conflicts')
    op.drop_table('evidence_conflicts')
    op.drop_index(op.f('ix_market_features_market_id'), table_name='market_features')
    op.drop_index(op.f('ix_market_features_known_at'), table_name='market_features')
    op.drop_index(op.f('ix_market_features_feature_set_version'), table_name='market_features')
    op.drop_index('ix_market_features_category_known', table_name='market_features')
    op.drop_index(op.f('ix_market_features_category'), table_name='market_features')
    op.drop_table('market_features')
    # ### end Alembic commands ###
